"""PDF artifact creation with per-user ownership and atomic writes."""

from __future__ import annotations

import os
import re
import tempfile
from collections.abc import Iterable
from datetime import UTC, datetime
from html import escape
from pathlib import Path
from uuid import uuid4

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
)

from .schemas import Artifact, Source

_ARTIFACT_ID = re.compile(r"^[0-9a-f]{32}$")


class ReportService:
    def __init__(self, artifact_dir: Path, max_characters: int = 100_000):
        self.artifact_dir = artifact_dir
        self.max_characters = max_characters

    def prepare(self) -> None:
        self.artifact_dir.mkdir(parents=True, exist_ok=True)

    def create(
        self,
        *,
        owner_namespace: str,
        title: str,
        markdown: str,
        sources: Iterable[Source] = (),
    ) -> Artifact:
        if not title.strip() or len(title) > 200:
            raise ValueError("report title is invalid")
        if not markdown.strip() or len(markdown) > self.max_characters:
            raise ValueError("report content is invalid or too large")

        self.prepare()
        artifact_id = uuid4().hex
        final_path = self._path(owner_namespace, artifact_id)
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                prefix="report-", suffix=".pdf.tmp", dir=self.artifact_dir, delete=False
            ) as temporary:
                temporary_path = Path(temporary.name)
            self._render_pdf(temporary_path, title.strip(), markdown.strip(), tuple(sources))
            os.replace(temporary_path, final_path)
        finally:
            if temporary_path is not None and temporary_path.exists():
                temporary_path.unlink(missing_ok=True)

        return Artifact(
            id=artifact_id,
            title=title.strip(),
            size_bytes=final_path.stat().st_size,
            download_url=f"/v1/artifacts/{artifact_id}",
            created_at=datetime.now(UTC),
        )

    def find(self, owner_namespace: str, artifact_id: str) -> Path | None:
        if _ARTIFACT_ID.fullmatch(artifact_id) is None:
            return None
        path = self._path(owner_namespace, artifact_id)
        return path if path.is_file() else None

    def _path(self, owner_namespace: str, artifact_id: str) -> Path:
        return self.artifact_dir / f"{owner_namespace}_{artifact_id}.pdf"

    def _render_pdf(
        self,
        output_path: Path,
        title: str,
        markdown: str,
        sources: tuple[Source, ...],
    ) -> None:
        document = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            title=title,
            author="MicroManus",
            subject="Deep research report",
            leftMargin=20 * mm,
            rightMargin=20 * mm,
            topMargin=24 * mm,
            bottomMargin=20 * mm,
        )
        styles = self._styles()
        story: list[object] = [
            Paragraph(escape(title), styles["ReportTitle"]),
            Spacer(1, 5 * mm),
            Paragraph(
                f"Generated by MicroManus · {datetime.now(UTC).strftime('%d %B %Y, %H:%M UTC')}",
                styles["Meta"],
            ),
            Spacer(1, 4 * mm),
            HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#CBD5E1")),
            Spacer(1, 5 * mm),
        ]
        story.extend(self._markdown_story(markdown, styles))

        unique_sources = self._unique_sources(sources)
        if unique_sources:
            story.extend([PageBreak(), Paragraph("Sources", styles["Heading1"])])
            for index, source in enumerate(unique_sources, start=1):
                url = escape(str(source.url), quote=True)
                label = escape(source.title or str(source.url))
                snippet = escape(source.snippet)
                story.append(
                    Paragraph(
                        f'<b>{index}.</b> <a href="{url}" color="#2563EB">{label}</a>',
                        styles["BodyText"],
                    )
                )
                if snippet:
                    story.append(Paragraph(snippet, styles["SourceSnippet"]))
                story.append(Spacer(1, 2.5 * mm))

        def draw_page(canvas: Canvas, doc: SimpleDocTemplate) -> None:
            canvas.saveState()
            canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
            canvas.line(20 * mm, 14 * mm, A4[0] - 20 * mm, 14 * mm)
            canvas.setFillColor(colors.HexColor("#64748B"))
            canvas.setFont("Helvetica", 8)
            canvas.drawString(20 * mm, 9 * mm, "MicroManus research artifact")
            canvas.drawRightString(A4[0] - 20 * mm, 9 * mm, f"Page {doc.page}")
            canvas.restoreState()

        document.build(story, onFirstPage=draw_page, onLaterPages=draw_page)

    @staticmethod
    def _styles() -> dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        return {
            "ReportTitle": ParagraphStyle(
                "ReportTitle",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=25,
                leading=30,
                textColor=colors.HexColor("#0F172A"),
                alignment=TA_CENTER,
                spaceAfter=8,
            ),
            "Meta": ParagraphStyle(
                "Meta",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#64748B"),
                alignment=TA_CENTER,
            ),
            "Heading1": ParagraphStyle(
                "Heading1",
                parent=base["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=17,
                leading=21,
                textColor=colors.HexColor("#0F172A"),
                spaceBefore=10,
                spaceAfter=7,
            ),
            "Heading2": ParagraphStyle(
                "Heading2",
                parent=base["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=17,
                textColor=colors.HexColor("#1E293B"),
                spaceBefore=8,
                spaceAfter=5,
            ),
            "Heading3": ParagraphStyle(
                "Heading3",
                parent=base["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=11,
                leading=14,
                textColor=colors.HexColor("#334155"),
                spaceBefore=6,
                spaceAfter=4,
            ),
            "BodyText": ParagraphStyle(
                "BodyText",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9.5,
                leading=14.5,
                textColor=colors.HexColor("#1E293B"),
                spaceAfter=7,
                splitLongWords=True,
            ),
            "Bullet": ParagraphStyle(
                "Bullet",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9.5,
                leading=14,
                leftIndent=12,
                firstLineIndent=-8,
                bulletIndent=2,
                spaceAfter=4,
                textColor=colors.HexColor("#1E293B"),
            ),
            "Quote": ParagraphStyle(
                "Quote",
                parent=base["BodyText"],
                fontName="Helvetica-Oblique",
                fontSize=9,
                leading=13.5,
                leftIndent=10,
                borderColor=colors.HexColor("#94A3B8"),
                borderWidth=1,
                borderPadding=6,
                textColor=colors.HexColor("#475569"),
                spaceAfter=7,
            ),
            "Code": ParagraphStyle(
                "Code",
                parent=base["Code"],
                fontName="Courier",
                fontSize=7.5,
                leading=10.5,
                leftIndent=6,
                rightIndent=6,
                borderColor=colors.HexColor("#CBD5E1"),
                borderWidth=0.5,
                borderPadding=6,
                backColor=colors.HexColor("#F8FAFC"),
                spaceAfter=7,
            ),
            "SourceSnippet": ParagraphStyle(
                "SourceSnippet",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=8,
                leading=11,
                leftIndent=12,
                textColor=colors.HexColor("#64748B"),
            ),
        }

    def _markdown_story(self, markdown: str, styles: dict[str, ParagraphStyle]) -> list[object]:
        story: list[object] = []
        paragraph_lines: list[str] = []
        code_lines: list[str] = []
        in_code = False

        def flush_paragraph() -> None:
            if paragraph_lines:
                text = " ".join(line.strip() for line in paragraph_lines)
                story.append(Paragraph(escape(text), styles["BodyText"]))
                paragraph_lines.clear()

        for raw_line in markdown.splitlines():
            line = raw_line.rstrip()
            if line.strip().startswith("```"):
                flush_paragraph()
                if in_code:
                    story.append(Preformatted("\n".join(code_lines), styles["Code"]))
                    code_lines.clear()
                in_code = not in_code
                continue
            if in_code:
                code_lines.append(line)
                continue
            if not line.strip():
                flush_paragraph()
                continue
            heading = re.match(r"^(#{1,3})\s+(.+)$", line)
            if heading:
                flush_paragraph()
                story.append(
                    Paragraph(escape(heading.group(2)), styles[f"Heading{len(heading.group(1))}"])
                )
                continue
            bullet = re.match(r"^\s*[-*+]\s+(.+)$", line)
            numbered = re.match(r"^\s*(\d+)[.)]\s+(.+)$", line)
            if bullet or numbered:
                flush_paragraph()
                marker = "•" if bullet else f"{numbered.group(1)}."
                text = bullet.group(1) if bullet else numbered.group(2)
                story.append(Paragraph(f"{marker} {escape(text)}", styles["Bullet"]))
                continue
            if line.lstrip().startswith(">"):
                flush_paragraph()
                story.append(Paragraph(escape(line.lstrip()[1:].strip()), styles["Quote"]))
                continue
            if re.match(r"^[-*_]{3,}$", line.strip()):
                flush_paragraph()
                story.append(
                    HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1"))
                )
                story.append(Spacer(1, 2 * mm))
                continue
            paragraph_lines.append(line)

        flush_paragraph()
        if code_lines:
            story.append(Preformatted("\n".join(code_lines), styles["Code"]))
        return story

    @staticmethod
    def _unique_sources(sources: tuple[Source, ...]) -> tuple[Source, ...]:
        seen: set[str] = set()
        result: list[Source] = []
        for source in sources:
            url = str(source.url)
            if url not in seen:
                seen.add(url)
                result.append(source)
        return tuple(result)
